#! /usr/bin/env bash
set -e # stop the execution of the script if it fails

# workspaces in github codespaces
FUNC_DIR="/workspaces/aws-bootcamp-cruddur-2023/ddb/function"
TEMPLATE_PATH="/workspaces/aws-bootcamp-cruddur-2023/ddb/template.yaml"
CONFIG_PATH="/workspaces/aws-bootcamp-cruddur-2023/ddb/config.toml"

sam validate -t $TEMPLATE_PATH

echo "== build"

sam build \
--use-container \
--config-file $CONFIG_PATH \
--template $TEMPLATE_PATH \
--base-dir $FUNC_DIR
#--parameter-overrides